[build]
publish = "public"
command = "zola build"

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it.
ZOLA_VERSION = "0.21.0"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=63072000; includeSubdomains"
# To update the style-src value, run one of the following commands:
# linux (coreutils)
# cksum --algorithm sha256 --base64 < templates/style.css.html | cut -d' ' -f 4
# macOS (should also work on linux if xxd is installed)
# shasum --algorithm 256 templates/style.css.html | cut -d' ' -f 1 | xxd -r -p | base64
# if nothing else works
# openssl dgst -sha256 -binary < templates/style.css.html | openssl enc -base64
# and paste the output after sha256-
Content-Security-Policy = "default-src 'none'; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://github.githubassets.com; object-src 'none'; script-src 'self' https://giscus.app; style-src 'self' 'unsafe-inline' 'sha256-p5EfRIhWJi7Zh7WJil3mpIVCZvcu+zebWbMe6B0so8A=' https://fonts.googleapis.com; form-action 'none'; base-uri 'self'; frame-ancestors 'none'; frame-src https://giscus.app; connect-src 'self' https://api.github.com"
Cross-Origin-Resource-Policy = "same-site"
Cache-Control = '''
  max-age=300,
  s-maxage=86400,
  stale-while-revalidate
'''
